<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.13">
  <POU Name="Test" Id="{45ae4d52-4131-4c96-aad5-0de207b3d4c3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Test
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Feste Geschwindigkeit und Winkel festlegen
GVL_Datatransfer23.gvFahrvektor.reGeschwindigkeit := 100;
GVL_Datatransfer23.gvFahrvektor.reWinkel := 0;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>